[package]
name = "koryto"
version = "0.0.2"
edition = "2021"
description = "ğŸ® game loop + ğŸ· coroutine + ğŸŒ¯ burrito = ğŸš€ğŸ”¥ blazingly synchronous async executor for games ğŸ”¥ğŸš€"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
